echo "all variables passed to the script $1 $2 $3"
echo "How many variables passed:$#"
echo "script name is $0"
echo "user name is : $USER"
echo  "pwd is $PWD"
echo "home directory is $HOME"
echo "line m=numbers is:$LINENO"
echo "sript executed in seconds:$SECONDS"
echo "Randon number generate"$RANDOM"